### PR TITLE
Add option to view available color schemes

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Right now there is no way to view the available color schemes that the user can use. This commit adds an option to do so.

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
Any updates on this pull request? Is this project dead?

**Comment by zadjii-msft** [comment]
@hugo-vrijswijk Hey sorry for the delay, I've been putting off ColorTool work for a while as I've been swamped with a lot of other dev work. I'll likely be able to come through and merge a bunch of pull requests next week. Thanks for your patience :)

**Comment by andot** [comment]
The next week is too looooong.

**Comment by miniksa** [comment]
Looking at this now. I've merged it and added an option to suppress the chattering errors when parsers fail to parse so when the INI parser misses against the Iterm files (since it goes first by alphabetical order in the reflective loading of the parsers), it doesn't spew output that disrupts the format of the table.

**Comment by miniksa** [comment]
OK, manually merged.

**Pull request merged**
