### PR TITLE
Use simpler csproj format

### PR DESCRIPTION
**Pull request by twsouthwick**
This project is fairly simple right now, but the older style csproj format that it is using can cause issues as a project grows especially concerning merge conflicts. As long as required development on VS 2017 is okay, this new format is much cleaner and simpler than the older project files.

### CODE REVIEW

**Comment by simonbuchan** [comment]
Wait, you can use the core csproj for full framework projects? Why isn't this default?

**Comment by twsouthwick** [comment]
Because it doesn't work for all project types. Simple console style apps, though, work as expected. Others (like WebApps, WPF, etc), have issues at the moment (although the team is working to enable it for all). It is default, however, if you go through the ".NET Core -> Console App" menu and then change it to a whatever target framework (ie .NET 4.6) you want.

**Comment by simonbuchan** [comment]
Thanks! That makes sense. (I mean, except for the creating a netfx app via ".NET Core" 😉) Having looked at some of the msbuild .props and .targets now, I can see why it's taking time!

**Comment by miniksa** [comment]
Sure this looks way simpler for a little tool like this.

**Pull request merged**
