### PR TITLE
Add support for parsing concfg presets

### LINKED ISSUE #62: concfg support ?
https://github.com/lukesampson/concfg

concfg looks like a really interesting tool, providing a large amount of settings for the windows console.

I wonder if it's worth the color tool being able to natively import concfg json files ?

### PR DESCRIPTION
**Pull request by devhawk**
concfg (https://github.com/lukesampson/concfg) is a tool that can import and export console settings. It includes a set of settings presets that includes color settings. This PR updates colortool to understand that format, so these presets can be used by colortool to change the colors of the current console session w/o affecting the defaults. 

Should close #62

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Looks great to me. Thanks!

**Comment by devhawk** [comment]
No prob. When will there be another release that includes this change? (Adding @bitcrazed for visibility)

**Comment by zadjii-msft** [comment]
I'm not totally sure, @bitcrazed was supposed to be taking care of getting a new official release out...

**Comment by bitcrazed** [comment]
Won't be until next week, but will definitely ping you once I get going on that.

**Pull request merged**
